# Use an official Node.js runtime as a parent image
FROM node:20.14.0

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 8003
EXPOSE 8003

# Command to run the application
CMD ["node", "server.js"]
